# Generated by Django 5.0.1 on 2024-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quote",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
