# Generated by Django 5.0.1 on 2024-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_user_bio_user_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="blink_board",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
