# Generated by Django 5.0.1 on 2024-01-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_user_avatar_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
