# Generated by Django 5.0.1 on 2024-01-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blink_board_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blink_board_image"
            ),
        ),
    ]
