# Generated by Django 5.0.1 on 2024-01-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_friend_status_friendrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendRequest",
        ),
    ]
